version: '3.8' # Define la versión de Docker Compose

services:
  eureka-server:
    image: openjdk:17-jdk-alpine
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    volumes:
      - ./eureka:/app
    command: ["java", "-jar", "eureka-server.jar"]

  usuarios-servicio:
    image: usuarios-servicio:1.0
    container_name: usuarios-servicio
    depends_on:
      - eureka-server
    ports:
      - "8080:8080"
    environment:
      - EUREKA_SERVER_URI=http://eureka-server:8761/eureka
    volumes:
      - ./usuarios:/app

  asignaturas-servicio:
    image: asignaturas-servicio:1.0
    container_name: asignaturas-servicio
    depends_on:
      - eureka-server
    ports:
      - "8081:8081"
    environment:
      - EUREKA_SERVER_URI=http://eureka-server:8761/eureka
    volumes:
      - ./asignaturas:/app

  matriculas-servicio:
    image: matriculas-servicio:1.0
    container_name: matriculas-servicio
    depends_on:
      - eureka-server
    ports:
      - "8082:8082"
    environment:
      - EUREKA_SERVER_URI=http://eureka-server:8761/eureka
    volumes:
      - ./matriculas:/app

networks:
  default:
    driver: bridge