management:
  endpoints:
    web:
      exposure:
        include: "*"  # Exponer todos los endpoints (puedes restringirlos según necesidad)
  endpoint:
    health:
      show-details: always  # Mostrar detalles completos en el endpoint de salud
  metrics:
    tags:
      application: usuarios-servicio  # Etiqueta para identificar métricas de este servicio